### PR TITLE
added stateHandler callback for client use

### PR DESCRIPTION
**Pull request by jtlapp**
Just a simple change. There is now a stateHandler config var that optionally takes a function to be called whenever the first item is added to the cart or the last is removed. When the first item is added, the function receives a URL to the checkout page. This allows the hosting site to provide a checkout link outside of our shopping cart. You can see it in operation at http://Jopodia.com

### CODE REVIEW

**Comment by RobertSpread** [comment]
there is a merge conflict I need to check. Currently I am not able to merge

**Comment by jtlapp** [comment]
How do  you look at the conflicts? I don't see them. I suspect it has something to do with having reverted commits.

**Comment by jtlapp** [comment]
This stackoverflow says that merge conflicts have to be resolved from the command line and suggests doing that from a side branch. I'll cancel this pull request and see if I can do this myself.

http://stackoverflow.com/questions/26096829/git-conflicts-in-pull-requests

**Comment by jtlapp** [comment]
Yeah, that was the problem. It complained anywhere I changed code that had been reverted. I don't think it understood that the reverted code was older code within the same branch.

**Pull request closed without merging**
